"""Make the logo string"""

def logo():
    """return logo str"""
    lg = ""
    lg += "##############################################\n"
    lg += "#                                            #\n"
    lg += "#    ggggggggggggggggg    ggggggggggggggggg  #\n"
    lg += "#   g::::::::::::::::g   g::::::::::::::::g  #\n"
    lg += "#  g:::::::::::::::::g  g:::::::::::::::::g  #\n"
    lg += "#  g::::::ggggg::::::g  g::::::ggggg::::::g  #\n"
    lg += "#  g:::::g     g:::::g  g:::::g     g:::::g  #\n"
    lg += "#  g:::::g     g:::::g  g:::::g     g:::::g  #\n"
    lg += "#  g:::::g     g:::::g  g:::::g     g:::::g  #\n"
    lg += "#  g::::::g    g:::::g  g::::::g    g:::::g  #\n"
    lg += "#  g:::::::ggggg:::::g  g:::::::ggggg:::::g  #\n"
    lg += "#   g::::::::::::::::g   g::::::::::::::::g  #\n"
    lg += "#    gg::::::::::::::g    gg::::::::::::::g  #\n"
    lg += "#      gggggggg::::::g      gggggggg::::::g  #\n"
    lg += "#              g:::::g              g:::::g  #\n"
    lg += "#  gggggg      g:::::g  gggggg      g:::::g  #\n"
    lg += "#  g:::::gg   gg:::::g  g:::::gg   gg:::::g  #\n"
    lg += "#   g::::::ggg:::::::g   g::::::ggg:::::::g  #\n"
    lg += "#    gg:::::::::::::g     gg:::::::::::::g   #\n"
    lg += "#      ggg::::::ggg         ggg::::::ggg     #\n"
    lg += "#         gggggg               gggggg        #\n"
    lg += "#                                            #\n"
    lg += "#############################################\n"

    return lg
